export const fuel = ["Wszystkie", "Benzyna", "Diesel", "Hybryda", "LPG", "CNG", "Elektryczny"]

const year = [2021, 2020, 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005, 2004, 2003, 2002, 2001, 2000, 1999, 1998, 1997, 1996, 1995, 1994, 1993, 1992, 1991, 1990, 1989, 1988, 1987, 1986, 1985, 1984, 1983, 1982, 1981, 1980]
export const yearFrom = ["od", ...year]
export const yearTo = ["do", ...year]

export const gearbox = ["Wszystkie", "Manualna", "Automatyczna"]




// ----------------------- START REGIONS ARRAY --------------------------//

// jest 16 wojwództw

export const regions = [
    "Wszystkie",
    "dolnośląskie",
    "kujawsko - pomorskie",
    "lubelskie",
    "lubuskie",
    "łódzkie",
    "małopolskie",
    "mazowieckie",
    "opolskie",
    "podkarpackie",
    "podlaskie",
    "pomorskie",
    "śląskie",
    "świętokrzyskie",
    "warmińsko - mazurskie",
    "wielkopolskie",
    "zachodniopomorskie",]

//wyodrębniono 218 miast w całej polsce powyżej 20tyś mieszkańców z podziałem na 16 województw (muszą być identyczne jak w const regions), wzięte z https://www.polskawliczbach.pl/Miasta (plik zapisany na dysku bez zbędnych kolumn)
export const cities = [
    { city: "Wszystkie", region: "Wszystkie" },
    { city: "Wszystkie", region: "dolnośląskie" },
    { city: "Wszystkie", region: "kujawsko - pomorskie" },
    { city: "Wszystkie", region: "lubelskie" },
    { city: "Wszystkie", region: "lubuskie" },
    { city: "Wszystkie", region: "łódzkie" },
    { city: "Wszystkie", region: "małopolskie" },
    { city: "Wszystkie", region: "mazowieckie" },
    { city: "Wszystkie", region: "opolskie" },
    { city: "Wszystkie", region: "podkarpackie" },
    { city: "Wszystkie", region: "podlaskie" },
    { city: "Wszystkie", region: "pomorskie" },
    { city: "Wszystkie", region: "śląskie" },
    { city: "Wszystkie", region: "świętokrzyskie" },
    { city: "Wszystkie", region: "warmińsko - mazurskie" },
    { city: "Wszystkie", region: "wielkopolskie" },
    { city: "Wszystkie", region: "zachodniopomorskie" },
    { city: "Warszawa", region: "mazowieckie" },
    { city: "Kraków", region: "małopolskie" },
    { city: "Łódź", region: "łódzkie" },
    { city: "Wrocław", region: "dolnośląskie" },
    { city: "Poznań", region: "wielkopolskie" },
    { city: "Gdańsk", region: "pomorskie" },
    { city: "Szczecin", region: "zachodniopomorskie" },
    { city: "Bydgoszcz", region: "kujawsko - pomorskie" },
    { city: "Lublin", region: "lubelskie" },
    { city: "Białystok", region: "podlaskie" },
    { city: "Katowice", region: "śląskie" },
    { city: "Gdynia", region: "pomorskie" },
    { city: "Częstochowa", region: "śląskie" },
    { city: "Radom", region: "mazowieckie" },
    { city: "Toruń", region: "kujawsko - pomorskie" },
    { city: "Sosnowiec", region: "śląskie" },
    { city: "Rzeszów", region: "podkarpackie" },
    { city: "Kielce", region: "świętokrzyskie" },
    { city: "Gliwice", region: "śląskie" },
    { city: "Zabrze", region: "śląskie" },
    { city: "Olsztyn", region: "warmińsko - mazurskie" },
    { city: "Bielsko - Biała", region: "śląskie" },
    { city: "Bytom", region: "śląskie" },
    { city: "Zielona Góra", region: "lubuskie" },
    { city: "Rybnik", region: "śląskie" },
    { city: "Ruda Śląska", region: "śląskie" },
    { city: "Opole", region: "opolskie" },
    { city: "Tychy", region: "śląskie" },
    { city: "Gorzów Wielkopolski", region: "lubuskie" },
    { city: "Płock", region: "mazowieckie" },
    { city: "Dąbrowa Górnicza", region: "śląskie" },
    { city: "Elbląg", region: "warmińsko - mazurskie" },
    { city: "Wałbrzych", region: "dolnośląskie" },
    { city: "Włocławek", region: "kujawsko - pomorskie" },
    { city: "Tarnów", region: "małopolskie" },
    { city: "Chorzów", region: "śląskie" },
    { city: "Koszalin", region: "zachodniopomorskie" },
    { city: "Kalisz", region: "wielkopolskie" },
    { city: "Legnica", region: "dolnośląskie" },
    { city: "Grudziądz", region: "kujawsko - pomorskie" },
    { city: "Jaworzno", region: "śląskie" },
    { city: "Słupsk", region: "pomorskie" },
    { city: "Jastrzębie - Zdrój", region: "śląskie" },
    { city: "Nowy Sącz", region: "małopolskie" },
    { city: "Jelenia Góra", region: "dolnośląskie" },
    { city: "Siedlce", region: "mazowieckie" },
    { city: "Mysłowice", region: "śląskie" },
    { city: "Konin", region: "wielkopolskie" },
    { city: "Piła", region: "wielkopolskie" },
    { city: "Piotrków Trybunalski", region: "łódzkie" },
    { city: "Inowrocław", region: "kujawsko - pomorskie" },
    { city: "Lubin", region: "dolnośląskie" },
    { city: "Ostrów Wielkopolski", region: "wielkopolskie" },
    { city: "Suwałki", region: "podlaskie" },
    { city: "Ostrowiec Świętokrzyski", region: "świętokrzyskie" },
    { city: "Gniezno", region: "wielkopolskie" },
    { city: "Stargard", region: "zachodniopomorskie" },
    { city: "Głogów", region: "dolnośląskie" },
    { city: "Siemianowice Śląskie", region: "śląskie" },
    { city: "Pabianice", region: "łódzkie" },
    { city: "Leszno", region: "wielkopolskie" },
    { city: "Zamość", region: "lubelskie" },
    { city: "Łomża", region: "podlaskie" },
    { city: "Żory", region: "śląskie" },
    { city: "Pruszków", region: "mazowieckie" },
    { city: "Ełk", region: "warmińsko - mazurskie" },
    { city: "Tomaszów Mazowiecki", region: "łódzkie" },
    { city: "Chełm", region: "lubelskie" },
    { city: "Tarnowskie Góry", region: "śląskie" },
    { city: "Przemyśl", region: "podkarpackie" },
    { city: "Kędzierzyn - Koźle", region: "opolskie" },
    { city: "Stalowa Wola", region: "podkarpackie" },
    { city: "Mielec", region: "podkarpackie" },
    { city: "Tczew", region: "pomorskie" },
    { city: "Biała Podlaska", region: "lubelskie" },
    { city: "Bełchatów", region: "łódzkie" },
    { city: "Świdnica", region: "dolnośląskie" },
    { city: "Będzin", region: "śląskie" },
    { city: "Zgierz", region: "łódzkie" },
    { city: "Piekary Śląskie ", region: "śląskie" },
    { city: "Racibórz", region: "śląskie" },
    { city: "Legionowo", region: "mazowieckie" },
    { city: "Ostrołęka", region: "mazowieckie" },
    { city: "Świętochłowice", region: "śląskie" },
    { city: "Wejherowo", region: "pomorskie" },
    { city: "Rumia", region: "pomorskie" },
    { city: "Zawiercie", region: "śląskie" },
    { city: "Piaseczno", region: "mazowieckie" },
    { city: "Starachowice", region: "świętokrzyskie" },
    { city: "Skierniewice", region: "łódzkie" },
    { city: "Wodzisław Śląski", region: "śląskie" },
    { city: "Starogard Gdański", region: "pomorskie" },
    { city: "Puławy", region: "lubelskie" },
    { city: "Tarnobrzeg", region: "podkarpackie" },
    { city: "Krosno", region: "podkarpackie" },
    { city: "Kołobrzeg", region: "zachodniopomorskie" },
    { city: "Radomsko", region: "łódzkie" },
    { city: "Dębica", region: "podkarpackie" },
    { city: "Skarżysko - Kamienna", region: "świętokrzyskie" },
    { city: "Otwock", region: "mazowieckie" },
    { city: "Ciechanów", region: "mazowieckie" },
    { city: "Kutno", region: "łódzkie" },
    { city: "Nysa", region: "opolskie" },
    { city: "Sieradz", region: "łódzkie" },
    { city: "Zduńska Wola", region: "łódzkie" },
    { city: "Mikołów", region: "śląskie" },
    { city: "Mińsk Mazowiecki", region: "mazowieckie" },
    { city: "Świnoujście", region: "zachodniopomorskie" },
    { city: "Szczecinek", region: "zachodniopomorskie" },
    { city: "Żyrardów", region: "mazowieckie" },
    { city: "Chojnice", region: "pomorskie" },
    { city: "Świdnik", region: "lubelskie" },
    { city: "Bolesławiec", region: "dolnośląskie" },
    { city: "Nowa Sól", region: "lubuskie" },
    { city: "Kwidzyn", region: "pomorskie" },
    { city: "Malbork", region: "pomorskie" },
    { city: "Knurów", region: "śląskie" },
    { city: "Oświęcim", region: "małopolskie" },
    { city: "Ząbki", region: "mazowieckie" },
    { city: "Jarosław", region: "podkarpackie" },
    { city: "Sanok", region: "podkarpackie" },
    { city: "Żary", region: "lubuskie" },
    { city: "Oleśnica", region: "dolnośląskie" },
    { city: "Wołomin", region: "mazowieckie" },
    { city: "Chrzanów", region: "małopolskie" },
    { city: "Sochaczew", region: "mazowieckie" },
    { city: "Czechowice - Dziedzice", region: "śląskie" },
    { city: "Sopot", region: "pomorskie" },
    { city: "Brzeg", region: "opolskie" },
    { city: "Marki", region: "mazowieckie" },
    { city: "Lębork", region: "pomorskie" },
    { city: "Olkusz", region: "małopolskie" },
    { city: "Jasło", region: "podkarpackie" },
    { city: "Cieszyn", region: "śląskie" },
    { city: "Kraśnik", region: "lubelskie" },
    { city: "Iława", region: "warmińsko - mazurskie" },
    { city: "Nowy Targ", region: "małopolskie" },
    { city: "Dzierżoniów", region: "dolnośląskie" },
    { city: "Oława", region: "dolnośląskie" },
    { city: "Ostróda", region: "warmińsko - mazurskie" },
    { city: "Police", region: "zachodniopomorskie" },
    { city: "Grodzisk Mazowiecki", region: "mazowieckie" },
    { city: "Luboń", region: "wielkopolskie" },
    { city: "Myszków", region: "śląskie" },
    { city: "Czeladź", region: "śląskie" },
    { city: "Pruszcz Gdański", region: "pomorskie" },
    { city: "Mława", region: "mazowieckie" },
    { city: "Żywiec", region: "śląskie" },
    { city: "Września", region: "wielkopolskie" },
    { city: "Zgorzelec", region: "dolnośląskie" },
    { city: "Swarzędz", region: "wielkopolskie" },
    { city: "Augustów", region: "podlaskie" },
    { city: "Bielawa", region: "dolnośląskie" },
    { city: "Łuków", region: "lubelskie" },
    { city: "Bochnia", region: "małopolskie" },
    { city: "Śrem", region: "wielkopolskie" },
    { city: "Giżycko", region: "warmińsko - mazurskie" },
    { city: "Brodnica", region: "kujawsko - pomorskie" },
    { city: "Krotoszyn", region: "wielkopolskie" },
    { city: "Nowy Dwór Mazowiecki", region: "mazowieckie" },
    { city: "Łowicz", region: "łódzkie" },
    { city: "Czerwionka - Leszczyny", region: "śląskie" },
    { city: "Gorlice", region: "małopolskie" },
    { city: "Kętrzyn", region: "warmińsko - mazurskie" },
    { city: "Zakopane", region: "małopolskie" },
    { city: "Wyszków", region: "mazowieckie" },
    { city: "Turek", region: "wielkopolskie" },
    { city: "Kłodzko", region: "dolnośląskie" },
    { city: "Biłgoraj", region: "lubelskie" },
    { city: "Reda", region: "pomorskie" },
    { city: "Jarocin", region: "wielkopolskie" },
    { city: "Pszczyna", region: "śląskie" },
    { city: "Wągrowiec", region: "wielkopolskie" },
    { city: "Żagań", region: "lubuskie" },
    { city: "Świecie", region: "kujawsko - pomorskie" },
    { city: "Bielsk Podlaski", region: "podlaskie" },
    { city: "Wałcz", region: "zachodniopomorskie" },
    { city: "Kobyłka", region: "mazowieckie" },
    { city: "Skawina", region: "małopolskie" },
    { city: "Białogard", region: "zachodniopomorskie" },
    { city: "Kościan", region: "wielkopolskie" },
    { city: "Wieliczka", region: "małopolskie" },
    { city: "Lubliniec", region: "śląskie" },
    { city: "Kościerzyna", region: "pomorskie" },
    { city: "Środa Wielkopolska", region: "wielkopolskie" },
    { city: "Kluczbork", region: "opolskie" },
    { city: "Sandomierz", region: "świętokrzyskie" },
    { city: "Bartoszyce", region: "warmińsko - mazurskie" },
    { city: "Szczytno", region: "warmińsko - mazurskie" },
    { city: "Jawor", region: "dolnośląskie" },
    { city: "Świebodzice", region: "dolnośląskie" },
    { city: "Piastów", region: "mazowieckie" },
    { city: "Polkowice", region: "dolnośląskie" },
    { city: "Ostrów Mazowiecka", region: "mazowieckie" },
    { city: "Wieluń", region: "łódzkie" },
    { city: "Goleniów", region: "zachodniopomorskie" },
    { city: "Łaziska Górne", region: "śląskie" },
    { city: "Płońsk", region: "mazowieckie" },
    { city: "Zambrów", region: "podlaskie" },
    { city: "Nowa Ruda", region: "dolnośląskie" },
    { city: "Grajewo", region: "podlaskie" },
    { city: "Lubartów", region: "lubelskie" },
    { city: "Aleksandrów Łódzki", region: "łódzkie" },
    { city: "Koło", region: "wielkopolskie" },
    { city: "Świebodzin", region: "lubuskie" },
    { city: "Mrągowo", region: "warmińsko - mazurskie" },
    { city: "Rydułtowy", region: "śląskie" },
    { city: "Działdowo", region: "warmińsko - mazurskie" },
    { city: "Orzesze", region: "śląskie" },
    { city: "Gryfino", region: "zachodniopomorskie" },
    { city: "Opoczno", region: "łódzkie" },
    { city: "Prudnik", region: "opolskie" },
    { city: "Lubań", region: "dolnośląskie" },
    { city: "Józefów", region: "mazowieckie" },
    { city: "Hajnówka", region: "podlaskie" },
    { city: "Gostyń", region: "wielkopolskie" },
    { city: "Rawicz", region: "wielkopolskie" },
    { city: "Andrychów", region: "małopolskie" },
]


// ----------------------- STOP REGIONS ARRAY --------------------------//





// ----------------------- START CARS ARRAY --------------------------//

// lista samochodów z olx + dodano jeszcze busy + zaktualizowano w oparciu o autocentrum ze stycznia 2021, jest 42 marki samochodów i około 822 modeli

const alfaromeo = {
    id: "alfaromeo", name: "Alfa Romeo", models: [
        "Wszystkie",
        "33",
        "75",
        "145",
        "146",
        "147",
        "155",
        "156",
        "159",
        "164",
        "166",
        "Brera",
        "Crosswagon",
        "Giulia",
        "Giulietta",
        "GT",
        "GTV",
        "Mito",
        "Spider",
        "Sportwagon",
        "Stelvio",
        "Pozostałe",]
}

const audi = {
    id: "audi", name: "Audi", models: [
        "Wszystkie",
        "A1",
        "A2",
        "A3",
        "A4",
        "A5",
        "A6",
        "A7",
        "A8",
        "Cabriolet",
        "Coupe",
        "E-tron",
        "Q2",
        "Q3",
        "Q5",
        "Q7",
        "Q8",
        "R8",
        "Rs4",
        "Rs6",
        "S2",
        "S3",
        "S4",
        "S5",
        "S6",
        "S8",
        "TT",
        "Pozostałe",]
}

const bmw = {
    id: "bmw", name: "BMW", models: [
        "Wszystkie",
        "i3",
        "i8",
        "M1",
        "M3",
        "M5",
        "M6",
        "Seria 1",
        "Seria 2",
        "Seria 3",
        "Seria 4",
        "Seria 5",
        "Seria 6",
        "Seria 7",
        "Seria 8",
        "X1",
        "X2",
        "X3",
        "X4",
        "X5",
        "X6",
        "X7",
        "Z3",
        "Z4",
        "Z8",
        "Pozostałe",]
}

const cadillac = {
    id: "cadillac", name: "Cadillac", models: [
        "Wszystkie",
        "Cts",
        "Deville",
        "Dts",
        "Eldorado",
        "Escalade",
        "Fleetwood",
        "SRX",
        "Pozostałe",]
}

const chevrolet = {
    id: "chevrolet", name: "Chevrolet", models: [
        "Wszystkie",
        "Alero",
        "Astro",
        "Avalanche",
        "Aveo",
        "Blazer",
        "Camaro",
        "Captiva",
        "Corvette",
        "Cruze",
        "Epica",
        "Equinox",
        "Evanda",
        "HHR",
        "Kalos",
        "Lacetti",
        "Malibu",
        "Matiz",
        "Orlando",
        "Rezzo",
        "Silverado",
        "Spark",
        "Suburban",
        "Tahoe",
        "TrailBlazer",
        "Trans Sport",
        "Trax",
        "Venture",
        "Volt",
        "Pozostałe",]
}

const chrysler = {
    id: "chrysler", name: "Chrysler", models: [
        "Wszystkie",
        "300C",
        "300M",
        "Aspen",
        "Caravan",
        "Concorde",
        "Crossfire",
        "Grand Voyager",
        "Le Baron",
        "Neon",
        "New Yorker",
        "Pacifica",
        "PT Cruiser",
        "Sebring",
        "Stratus",
        "Town & Country",
        "Voyager",
        "Pozostałe",]
}

const citroen = {
    id: "citroen", name: "Citroen", models: [
        "Wszystkie",
        "AX",
        "Berlingo",
        "BX",
        "C-Crosser",
        "C-Elysee",
        "C1",
        "C2",
        "C3",
        "C3 Picasso",
        "C3 Pluriel",
        "C4",
        "C4 Cactus",
        "C4 Picasso",
        "C5",
        "C6",
        "C8",
        "CX",
        "DS",
        "Evasion",
        "GSA",
        "Jumper",
        "Nemo",
        "Saxo",
        "Spacetourer",
        "Xantia",
        "XM",
        "Xsara",
        "Xsara Picasso",
        "ZX",
        "Pozostałe",]
}

const dacia = {
    id: "dacia", name: "Dacia", models: [
        "Wszystkie",
        "Doker",
        "Duster",
        "Lodgy",
        "Logan",
        "Sandero",
        "Sandero Stepway",
        "Lodgy",
        "Pozostałe",]
}

const daewoo = {
    id: "daewoo", name: "Daewoo", models: [
        "Wszystkie",
        "Espero",
        "Kalos",
        "Korando",
        "Lanos",
        "Leganza",
        "Matiz",
        "Musso",
        "Nubira",
        "Rezzo",
        "Tacuma",
        "Tico",
        "Pozostałe",]
}

const daihatsu = {
    id: "daihatsu", name: "Daihatsu", models: [
        "Wszystkie",
        "Cuore",
        "Materia",
        "Move",
        "Sirion",
        "Feroza",
        "Terios",
        "Pozostałe",]
}

const dodge = {
    id: "dodge", name: "Dodge", models: [
        "Wszystkie",
        "Avenger",
        "Caliber",
        "Caravan",
        "Challenger",
        "Charger",
        "Durango",
        "Journey",
        "Grand Caravan",
        "Magnum",
        "Nitro",
        "Ram",
        "Stratus",
        "Pozostałe",]
}

const fiat = {
    id: "fiat", name: "Fiat", models: [
        "Wszystkie",
        "125p",
        "126",
        "500",
        "600",
        "Albea",
        "Barchetta",
        "Brava",
        "Bravo",
        "Cinquecento",
        "Coupe",
        "Croma",
        "Doblo",
        "Ducato",
        "Fiorino",
        "Freemont",
        "Grande Punto",
        "Idea",
        "Linea",
        "Marea",
        "Multipla",
        "Palio",
        "Panda",
        "Punto",
        "Punto Evo",
        "Scudo",
        "Sedici",
        "Seicento",
        "Siena",
        "Stilo",
        "Strada",
        "Tempra",
        "Tipo",
        "Qubo",
        "Ulysse",
        "Uno",
        "Pozostałe",]
}

const ford = {
    id: "ford", name: "Ford", models: [
        "Wszystkie",
        "Aerostar",
        "C-MAX",
        "Capri",
        "Cougar",
        "Econoline",
        "Ecosport",
        "Edge",
        "Edge Vignale",
        "Escape",
        "Escort",
        "Explorer",
        "F150",
        "F250",
        "F350",
        "Fiesta",
        "Fiesta Vignale",
        "Flex",
        "Focus",
        "Focus C-Max",
        "Focus Vignale",
        "Fusion",
        "Galaxy",
        "Granada",
        "Gt",
        "KA",
        "Kuga",
        "Maverick",
        "Mondeo",
        "Mondeo Vignale",
        "Mustang",
        "Orion",
        "Probe",
        "Puma",
        "Ranger",
        "S-Max",
        "Scorpio",
        "Sierra",
        "Streetka",
        "Taurus",
        "Tourneo",
        "Transit",
        "Windstar",
        "Pozostałe",]
}

const honda = {
    id: "honda", name: "Honda", models: [
        "Wszystkie",
        "Accord",
        "City",
        "Civic",
        "Concerto",
        "CR-V",
        "CRX",
        "e",
        "FR-V",
        "HR-V",
        "Insight",
        "Integra",
        "Jazz",
        "Legend",
        "NSX",
        "Odyssey",
        "Prelude",
        "S 2000",
        "Shuttle",
        "Stream",
        "Pozostałe",]
}

const hyundai = {
    id: "hyundai", name: "Hyundai", models: [
        "Wszystkie",
        "Accent",
        "Atos",
        "Coupe",
        "Elantra",
        "Getz",
        "H1",
        "H200",
        "i10",
        "i20",
        "i30",
        "i40",
        "IONIQ",
        "ix20",
        "ix35",
        "ix55",
        "Konta",
        "Lantra",
        "Santa Fe",
        "Sonata",
        "Terracan",
        "Tucson",
        "Veracruz",
        "Pozostałe",]
}

const infiniti = {
    id: "infiniti ", name: "Infiniti ", models: [
        "Wszystkie",
        "EX",
        "FX",
        "G",
        "M",
        "Q30",
        "Q50",
        "Q60",
        "Q70",
        "XQ",
        "XQ30",
        "XQ50",
        "XQ60",
        "XQ70",
        "Pozostałe",]
}

const jaguar = {
    id: "jaguar  ", name: "Jaguar  ", models: [
        "Wszystkie",
        "E-Pace",
        "E-Type",
        "F-Pace",
        "F-Type",
        "I-Pace",
        "S-Type",
        "X-Type",
        "XE",
        "XF",
        "XJ",
        "XJS",
        "XK",
        "Pozostałe",]
}

const jeep = {
    id: "jeep", name: "Jeep", models: [
        "Wszystkie",
        "Cherokee",
        "Commander",
        "Compass",
        "Grand Cherokee",
        "Liberty",
        "Patriot",
        "Renegade",
        "Wrangler",
        "Pozostałe",]
}

const kia = {
    id: "kia", name: "Kia", models: [
        "Wszystkie",
        "Carens",
        "Cee'd",
        "Cerato",
        "Niro",
        "Optima",
        "Picanto",
        "Procee'd",
        "Rio",
        "Sorento",
        "Soul",
        "Sportage",
        "Stinger",
        "Stonic",
        "Venga",
        "XCee'd",
        "Pozostałe",]
}

const lancia = {
    id: "lancia", name: "Lancia", models: [
        "Wszystkie",
        "Dedra",
        "Delta",
        "Kappa",
        "Lybra",
        "Musa",
        "Phedra",
        "Voyager",
        "Ypsilon",
        "Pozostałe",]
}

const landrover = {
    id: "landrover", name: "Land Rover", models: [
        "Wszystkie",
        "Defender",
        "Discovery",
        "Freelander",
        "Range Rover",
        "Velar",
        "Pozostałe",]
}

const lexus = {
    id: "lexus", name: "Lexus", models: [
        "Wszystkie",
        "CT",
        "ES",
        "GS",
        "GX",
        "HS",
        "IS",
        "LC",
        "LS",
        "LX",
        "NX",
        "RC",
        "RX",
        "UX",
        "Pozostałe",]
}

const mazda = {
    id: "mazda", name: "Mazda", models: [
        "Wszystkie",
        "2",
        "3",
        "5",
        "6",
        "CX-3",
        "CX-30",
        "CX-5",
        "CX-7",
        "CX-8",
        "CX-9",
        "MX-3",
        "MX-30",
        "MX-5",
        "MX-6",
        "RX-7",
        "RX-8",
        "Pozostałe",]
}

const mercedesbenz = {
    id: "mercedesbenz", name: "Mercedes-Benz", models: [
        "Wszystkie",
        "Klasa A",
        "Klasa B",
        "Klasa C",
        "Klasa E",
        "Klasa G",
        "Klasa M",
        "Klasa R",
        "Klasa S",
        "Klasa V",
        "CL",
        "CLA",
        "CLC",
        "CLK",
        "CLS",
        "EQC",
        "EQV",
        "GL",
        "GLA",
        "GLB",
        "GLC",
        "GLE",
        "GLK",
        "GLS",
        "Maybach",
        "ML",
        "SL",
        "SLC",
        "SLK",
        "Seria 190",
        "Seria 200",
        "Seria 300",
        "Citan",
        "Sprinter",
        "Vaneo",
        "Viano",
        "Vito",
        "W123",
        "W124",
        "Pozostałe",]
}

const mini = {
    id: "mini", name: "Mini", models: [
        "Wszystkie",
        "Cabrio",
        "Clubman",
        "Clubvan",
        "Cooper",
        "Cooper S",
        "Countryman",
        "Coupe",
        "Mini",
        "One",
        "Paceman",
        "Roadster",
        "Pozostałe",]
}

const mitsubishi = {
    id: "mitsubishi", name: "Mitsubishi", models: [
        "Wszystkie",
        "3000 GT",
        "ASX",
        "Carisma",
        "Colt",
        "Eclipse",
        "Endeavor",
        "Galant",
        "Grandis",
        "L200",
        "L400",
        "Lancer",
        "Lancer Evolution VII",
        "Lancer Evolution VIII",
        "Lancer Evolution IX",
        "Lancer Evolution X",
        "Montero",
        "Outlander",
        "Pajero",
        "Sigma",
        "Space Gear",
        "Space Runner",
        "Space Star",
        "Space Wagon",
        "Pozostałe",]
}

const nissan = {
    id: "nissan", name: "Nissan", models: [
        "Wszystkie",
        "100 NX",
        "200 SX",
        "300 ZX",
        "350 Z ",
        "370 Z",
        "Almera",
        "Altima",
        "Evalia",
        "Frontier",
        "GT-R",
        "Juke",
        "King Cab",
        "Leaf",
        "Maxima",
        "Micra",
        "Murano",
        "Navara",
        "New Micra",
        "Note",
        "NV200",
        "Pathfinder",
        "Patrol",
        "Pickup",
        "Pixo",
        "Prairie",
        "Primastar",
        "Primera",
        "Qashqai",
        "Quest ",
        "Sentra",
        "Serena",
        "Skyline",
        "Sunny",
        "Terrano",
        "Tiida",
        "X-Trail",
        "Pozostałe",]
}

const opel = {
    id: "opel", name: "Opel", models: [
        "Wszystkie",
        "Agila",
        "Antara",
        "Ascona",
        "Astra",
        "Calibra",
        "Campo",
        "Combo",
        "Corsa",
        "Crosslod",
        "Frontera",
        "GT",
        "Grandland",
        "Insignia",
        "Kadett",
        "Manta",
        "Meriva",
        "Mokka",
        "Monterey",
        "Movano",
        "Omega",
        "Rekord",
        "Senator",
        "Signum",
        "Sintra",
        "Tigra",
        "Vectra",
        "Vivaro",
        "Zafira",
        "Pozostałe",]
}

const peugeot = {
    id: "peugeot", name: "Peugeot", models: [
        "Wszystkie",
        "106",
        "107",
        "205",
        "206",
        "206 CC",
        "206 plus",
        "207",
        "207 CC",
        "208",
        "301",
        "306",
        "307",
        "308",
        "309",
        "404",
        "405",
        "406",
        "407",
        "508",
        "605",
        "607",
        "806",
        "807",
        "1007",
        "2008",
        "3008",
        "4007",
        "5008",
        "Boxer",
        "Bipper",
        "Expert",
        "Partner",
        "RCZ",
        "Rifter",
        "Traveller",
        "Pozostałe",]
}

const porsche = {
    id: "porsche", name: "Porsche", models: [
        "Wszystkie",
        "911",
        "924",
        "928",
        "944",
        "Boxster",
        "Carrera",
        "Cayenne",
        "Cayenne S",
        "Cayenne Turbo",
        "Cayman",
        "Macan",
        "Panamera",
        "Taycan",
        "Pozostałe",]
}

const renault = {
    id: "renault", name: "Renault", models: [
        "Wszystkie",
        "4",
        "5",
        "11",
        "19",
        "21",
        "Avantime",
        "Captur",
        "Clio",
        "Coupe",
        "Espace",
        "Fluence",
        "Grand Espace",
        "Grand Scenic",
        "Kadjar",
        "Kangoo",
        "Koleos",
        "Laguna",
        "Latitude",
        "Master",
        "Megane",
        "Modus",
        "Safrane",
        "Scenic",
        "Scenic Conquest",
        "Scenic RX4",
        "Talisman",
        "Thalia",
        "Trafic",
        "Twingo",
        "Vel Satis",
        "Zoe",
        "Pozostałe",]
}

const rover = {
    id: "rover", name: "Rover", models: [
        "Wszystkie",
        "25",
        "45",
        "75",
        "111",
        "200",
        "214",
        "216",
        "218",
        "220",
        "400",
        "414",
        "416",
        "418",
        "420",
        "600",
        "618",
        "620",
        "623",
        "820",
        "825",
        "827",
        "MG",
        "Pozostałe",]
}

const saab = {
    id: "saab", name: "Saab", models: [
        "Wszystkie",
        "9-3",
        "9-5",
        "9-7X",
        "900",
        "9000",
        "Pozostałe",]
}

const seat = {
    id: "seat", name: "Seat", models: [
        "Wszystkie",
        "Alhambra",
        "Altea",
        "Altea XL",
        "Arosa",
        "Arona",
        "Ateca",
        "Cordoba",
        "Exeo",
        "Ibiza",
        "Inca",
        "Leon",
        "Terra",
        "Tarraco",
        "Toledo",
        "Pozostałe",]
}

const skoda = {
    id: "skoda", name: "Skoda", models: [
        "Wszystkie",
        "Citigo",
        "Enyaq iV",
        "Fabia",
        "Kamiq",
        "Karoq",
        "Kodiaq",
        "Octavia",
        "Scala",
        "Rapid",
        "Roomster",
        "Superb",
        "Yeti",
        "Pozostałe",]
}

const smart = {
    id: "smart", name: "Smart", models: [
        "Wszystkie",
        "Fortwo",
        "Forfour",
        "Roadster",
        "Pozostałe",]
}

const ssangyong = {
    id: "ssangyong", name: "SsangYong", models: [
        "Wszystkie",
        "Korando",
        "Musso",
        "Kyron",
        "Rexton",
        "Tivoli",
        "XLV",
        "Pozostałe",]
}

const subaru = {
    id: "subaru", name: "Subaru", models: [
        "Wszystkie",
        "Forester",
        "Impreza",
        "Justy",
        "Legacy",
        "Outback",
        "Tribeca",
        "WRX STI",
        "XV",
        "Pozostałe",]
}

const suzuki = {
    id: "suzuki", name: "Suzuki", models: [
        "Wszystkie",
        "Across",
        "Alto",
        "Baleno",
        "Calerio",
        "Grand Vitara",
        "Ignis",
        "Jimny",
        "Liana",
        "Samurai",
        "SJ",
        "Splash",
        "Swace",
        "Swift",
        "SX4 ",
        "Vitara",
        "Wagon",
        "Pozostałe",]
}

const toyota = {
    id: "toyota", name: "Toyota", models: [
        "Wszystkie",
        "4Runner",
        "Auris",
        "Avalon",
        "Avensis",
        "Avensis Verso",
        "Aygo",
        "C-HR",
        "Camry",
        "Carina",
        "Celica",
        "Corolla",
        "Corolla Verso",
        "FJ",
        "GT86",
        "Highlander",
        "Hilux",
        "iQ",
        "Land Cruiser",
        "Matrix",
        "MR2",
        "Paseo",
        "Previa",
        "Prius",
        "Proace",
        "RAV4",
        "Sequoia",
        "Sienna",
        "Starlet",
        "Supra",
        "Tacoma",
        "Verso",
        "Yaris",
        "Yaris Hybrid",
        "Yaris Verso",
        "Pozostałe",]
}

const volkswagen = {
    id: "volkswagen", name: "Volkswagen", models: [
        "Wszystkie",
        "Amarok",
        "Arteon",
        "Beetle",
        "Bora",
        "Buggy",
        "CC",
        "Caddy",
        "Caravelle",
        "Corrado",
        "Crafter",
        "Eos",
        "Fox",
        "Garbus",
        "Golf",
        "Golf Plus",
        "ID.3",
        "ID.4",
        "Jetta",
        "Lupo",
        "Multivan",
        "New Beetle",
        "Passat",
        "Passat CC",
        "Phaeton",
        "Polo",
        "Scirocco",
        "Sharan",
        "T-Cross",
        "T-Roc",
        "Tiguan",
        "Touareg",
        "Touran",
        "Transporter",
        "Up!",
        "Vento",
        "Pozostałe",]
}

const volvo = {
    id: "volvo", name: "Volvo", models: [
        "Wszystkie",
        "C30",
        "C70",
        "S40",
        "S60",
        "S70",
        "S80",
        "S90",
        "V40",
        "V50",
        "V60",
        "V70",
        "V90",
        "XC40",
        "XC60",
        "XC70",
        "XC90",
        "Pozostałe",]
}


const wszystkie = {
    id: "Wszystkie", name: "Wszystkie", models: ["Wszystkie"]
}
//     "Alfa Romeo",
//     "Audi",
//     "BMW",
//     "Cadillac",
//     "Chevrolet",
//     "Chrysler",
//     "Citroen",
//     "Dacia",
//     "Daewoo",
//     "Daihatsu",
//     "Dodge",
//     "Fiat",
//     "Ford",
//     "Honda",
//     "Hyundai",
//     "Infiniti",
//     "Jaguar",
//     "Jeep",
//     "Kia",
//     "Lancia",
//     "Land Rover",
//     "Lexus",
//     "Mazda",
//     "Mercedes-Benz",
//     "Mini",
//     "Mitsubishi",
//     "Nissan",
//     "Opel",
//     "Peugeot",
//     "Porsche",
//     "Renault",
//     "Rover",
//     "Saab",
//     "Seat",
//     "Skoda",
//     "Smart",
//     "SsangYong",
//     "Subaru",
//     "Suzuki",
//     "Toyota",
//     "Volkswagen",
//     "Volvo",
//     "Pozostałe",


export const cars = [wszystkie, alfaromeo, audi, bmw, cadillac, chevrolet, chrysler, citroen, dacia, daewoo, daihatsu, dodge, fiat, ford, honda, hyundai, infiniti, jaguar, jeep, kia, lancia, landrover, lexus, mazda, mercedesbenz, mini, mitsubishi, nissan, opel, peugeot, porsche, renault, rover, saab, seat, skoda, smart, ssangyong, subaru, suzuki, toyota, volkswagen, volvo,]


// ----------------------- STOP CARS ARRAY --------------------------//

